### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by makma**
### Motivation

Update CODEOWNERS

### CODE REVIEW

**Comment by Simply007** [comment]
@makma - any idea why the build is failing on Gatsby Cloud?

**Comment by makma** [comment]
> @makma - any idea why the build is failing on Gatsby Cloud?

```
Couldn't find the "gatsby-plugin-google-fonts" plugin declared in "/usr/src/app/www/gatsby-config.js".
```

Maybe a dependency should be placed in steps instead of devDeps?

**Comment by Simply007** [comment]
It looks like multiple plugins are in dev dependencies:
https://github.com/Kentico/gatsby-starter-kontent-lumen/blob/update-codeowners/package.json#L49-L55

**Comment by makma** [comment]
Nice!

**Review by Simply007 — APPROVED** [review]

**Pull request merged**
